### ISSUE TITLE
Outdated Drop Charts

### ISSUE THREAD

**Issue by ghost** [SethClydesdale/psobb-drop-charts#2]
Drop charts are outdated on this add-on as of the Episode 1 drop chart rework on 10/7.

**Comment by SethClydesdale** [comment]
Hi,

Thanks for the info. I'll see if I can get around to updating this sometime.

**Comment by SethClydesdale** [comment]
Hey again,

Just to let you know, I've updated the addon with the new drop charts as well as made a few other changes. See the post I made on the forum for more information.

https://www.pioneer2.net/community/threads/psobb-addon-plugin-lua-ui-addons.4543/page-40#post-109502

Thanks again, and if anymore issues arise you can let me know.
